#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen.

alias afk="gnome-screensaver-command --lock"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `Advanced Packaging Tool`

alias apti="sudo apt-get install"
alias aptr="sudo apt-get remove"
alias apts="sudo apt-cache search"
alias aptu="sudo apt-get update \
                && sudo apt-get upgrade"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty trash.

alias empty-trash="rm -rf ~/.local/share/Trash/files/*"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update applications and CLTs.

alias u="sudo apt-get update \
            && sudo apt-get upgrade"
alias packages="find ./ -type f -name \"package.json\" -exec stat --format=\"%Y %n\" {} + | grep -v \"node_modules\" | sort -n | awk '{print strftime(\"%Y-%m-%d %H:%M:%S\", \$1), \$2}'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Network tools

alias local-ip='hostname -I | awk '\''{print $1}'\'''
alias myip='curl -s https://ipinfo.io/ip'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Raspberry Pi specific

alias pi-temp='vcgencmd measure_temp'
alias pi-throttle='vcgencmd get_throttled'
alias pi-version='cat /proc/device-tree/model'
