#!/bin/zsh
# Zsh functions loader
# Usage (add to .zshrc):
#   source ~/.dotfiles/src/os/macos/functions/zsh/main.sh

SCRIPT_DIR="${0:A:h}"

source "$SCRIPT_DIR/backup-all.sh"
source "$SCRIPT_DIR/backup-source.sh"
source "$SCRIPT_DIR/ccurl.sh"
source "$SCRIPT_DIR/claude-danger.sh"
source "$SCRIPT_DIR/clean-dev.sh"
source "$SCRIPT_DIR/clone.sh"
source "$SCRIPT_DIR/datauri.sh"
source "$SCRIPT_DIR/delete-files.sh"
source "$SCRIPT_DIR/docker-clean.sh"
source "$SCRIPT_DIR/dp.sh"
source "$SCRIPT_DIR/evm.sh"
source "$SCRIPT_DIR/fetch-github-repos.sh"
source "$SCRIPT_DIR/get-channel.sh"
source "$SCRIPT_DIR/get-course.sh"
source "$SCRIPT_DIR/get-dependencies.sh"
source "$SCRIPT_DIR/get-folder.sh"
source "$SCRIPT_DIR/get-tunes.sh"
source "$SCRIPT_DIR/get-video.sh"
source "$SCRIPT_DIR/git-backup.sh"
source "$SCRIPT_DIR/git-clone.sh"
source "$SCRIPT_DIR/git-pup.sh"
source "$SCRIPT_DIR/git-push.sh"
source "$SCRIPT_DIR/h.sh"
source "$SCRIPT_DIR/install-dependencies-from.sh"
source "$SCRIPT_DIR/ips.sh"
source "$SCRIPT_DIR/killni.sh"
source "$SCRIPT_DIR/mkd.sh"
source "$SCRIPT_DIR/ncu-update-all.sh"
source "$SCRIPT_DIR/npmi.sh"
source "$SCRIPT_DIR/org-by-date.sh"
source "$SCRIPT_DIR/refresh-files.sh"
source "$SCRIPT_DIR/remove-smaller-files.sh"
source "$SCRIPT_DIR/rename-files-with-date-in-name.sh"
source "$SCRIPT_DIR/resize-image.sh"
source "$SCRIPT_DIR/rm-safe.sh"
source "$SCRIPT_DIR/s.sh"
source "$SCRIPT_DIR/set-git-public.sh"
source "$SCRIPT_DIR/vpush.sh"
